"""Generate reviewable MySQL DDL from the application schema."""
from pathlib import Path
from sqlalchemy import create_mock_engine
from kernelguard.core import metadata

statements = ["-- Generated by python -m scripts.export_schema; select your database first."]
engine = create_mock_engine("mysql+pymysql://", lambda sql, *a, **kw:
    statements.append(str(sql.compile(dialect=engine.dialect)).strip() + ";"))
metadata.create_all(engine, checkfirst=False)
Path("sql/schema.mysql.sql").write_text("\n\n".join(statements) + "\n", encoding="utf-8")
