-- Generated by python -m scripts.export_schema; select your database first.

CREATE TABLE events (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	source_id VARCHAR(64) NOT NULL, 
	host VARCHAR(128) NOT NULL, 
	timestamp INTEGER NOT NULL, 
	kind VARCHAR(32) NOT NULL, 
	account VARCHAR(128) NOT NULL, 
	uid VARCHAR(32), 
	effective_uid VARCHAR(32), 
	session VARCHAR(64), 
	pid VARCHAR(32), 
	executable TEXT, 
	resource TEXT, 
	outcome VARCHAR(32) NOT NULL, 
	origin VARCHAR(16) NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (source_id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_bin;

CREATE INDEX ix_event_account_time ON events (host, account, timestamp);

CREATE INDEX ix_event_kind_time ON events (kind, timestamp);

CREATE TABLE alerts (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	dedup_key VARCHAR(64) NOT NULL, 
	rule VARCHAR(48) NOT NULL, 
	timestamp INTEGER NOT NULL, 
	account VARCHAR(128) NOT NULL, 
	score INTEGER NOT NULL, 
	reason TEXT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (dedup_key)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_bin;

CREATE TABLE checkpoints (
	name VARCHAR(128) NOT NULL, 
	value TEXT NOT NULL, 
	PRIMARY KEY (name)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_bin;

CREATE TABLE rule_policies (
	id VARCHAR(64) NOT NULL, 
	rule_code VARCHAR(48) NOT NULL, 
	version INTEGER NOT NULL, 
	parameters_json TEXT NOT NULL, 
	PRIMARY KEY (id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_bin;

CREATE TABLE alert_events (
	alert_id INTEGER NOT NULL, 
	event_id INTEGER NOT NULL, 
	PRIMARY KEY (alert_id, event_id), 
	FOREIGN KEY(alert_id) REFERENCES alerts (id), 
	FOREIGN KEY(event_id) REFERENCES events (id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_bin;

CREATE TABLE event_context (
	event_id INTEGER NOT NULL, 
	boot_id VARCHAR(64) NOT NULL, 
	PRIMARY KEY (event_id), 
	FOREIGN KEY(event_id) REFERENCES events (id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_bin;

CREATE TABLE audit_details (
	event_id INTEGER NOT NULL, 
	audit_timestamp VARCHAR(40) NOT NULL, 
	audit_serial VARCHAR(32) NOT NULL, 
	record_type VARCHAR(32) NOT NULL, 
	login_uid VARCHAR(32), 
	real_uid VARCHAR(32), 
	effective_uid VARCHAR(32), 
	session_id VARCHAR(64), 
	syscall VARCHAR(32), 
	architecture VARCHAR(32), 
	inode VARCHAR(32), 
	device VARCHAR(32), 
	PRIMARY KEY (event_id), 
	FOREIGN KEY(event_id) REFERENCES events (id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_bin;

CREATE TABLE alert_policies (
	alert_id INTEGER NOT NULL, 
	policy_id VARCHAR(64) NOT NULL, 
	PRIMARY KEY (alert_id), 
	FOREIGN KEY(alert_id) REFERENCES alerts (id), 
	FOREIGN KEY(policy_id) REFERENCES rule_policies (id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_bin;

CREATE INDEX ix_alert_policy ON alert_policies (policy_id);
