-- Generated by python -m scripts.export_schema; select your database first.

CREATE TABLE events (
	id INTEGER NOT NULL AUTO_INCREMENT,
	source_id VARCHAR(64) NOT NULL,
	host VARCHAR(128) NOT NULL,
	timestamp INTEGER NOT NULL,
	kind VARCHAR(32) NOT NULL,
	account VARCHAR(128) NOT NULL,
	uid VARCHAR(32),
	effective_uid VARCHAR(32),
	session VARCHAR(64),
	pid VARCHAR(32),
	executable TEXT,
	resource TEXT,
	outcome VARCHAR(32) NOT NULL,
	origin VARCHAR(16) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (source_id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_bin;

CREATE INDEX ix_event_account_time ON events (host, account, timestamp);

CREATE INDEX ix_event_kind_time ON events (kind, timestamp);

CREATE TABLE alerts (
	id INTEGER NOT NULL AUTO_INCREMENT,
	dedup_key VARCHAR(64) NOT NULL,
	rule VARCHAR(48) NOT NULL,
	timestamp INTEGER NOT NULL,
	account VARCHAR(128) NOT NULL,
	score INTEGER NOT NULL,
	reason TEXT NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (dedup_key)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE checkpoints (
	name VARCHAR(128) NOT NULL,
	value TEXT NOT NULL,
	PRIMARY KEY (name)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE rule_policies (
	id VARCHAR(64) NOT NULL,
	rule_code VARCHAR(48) NOT NULL,
	version INTEGER NOT NULL,
	parameters_json TEXT NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE administrators (
	id INTEGER NOT NULL AUTO_INCREMENT,
	username VARCHAR(64) NOT NULL,
	password_hash VARCHAR(256) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (username)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE inventory_snapshots (
	id VARCHAR(64) NOT NULL,
	host VARCHAR(128) NOT NULL,
	origin VARCHAR(16) NOT NULL,
	boot_id VARCHAR(64) NOT NULL,
	timestamp INTEGER NOT NULL,
	processes_complete BOOL NOT NULL,
	warnings_json TEXT NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_bin;

CREATE INDEX ix_snapshot_scope_time ON inventory_snapshots (host, origin, timestamp);

CREATE TABLE host_users (
	id VARCHAR(64) NOT NULL,
	host VARCHAR(128) NOT NULL,
	origin VARCHAR(16) NOT NULL,
	uid VARCHAR(32) NOT NULL,
	username VARCHAR(128) NOT NULL,
	last_seen INTEGER NOT NULL,
	present BOOL NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE usb_devices (
	id VARCHAR(64) NOT NULL,
	host VARCHAR(128) NOT NULL,
	origin VARCHAR(16) NOT NULL,
	vendor VARCHAR(4) NOT NULL,
	product VARCHAR(4) NOT NULL,
	serial VARCHAR(256),
	port VARCHAR(256) NOT NULL,
	label VARCHAR(256) NOT NULL,
	identity_basis VARCHAR(16) NOT NULL,
	boot_id VARCHAR(64) NOT NULL,
	first_seen INTEGER NOT NULL,
	last_seen INTEGER NOT NULL,
	present BOOL NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE alert_events (
	alert_id INTEGER NOT NULL,
	event_id INTEGER NOT NULL,
	PRIMARY KEY (alert_id, event_id),
	FOREIGN KEY(alert_id) REFERENCES alerts (id),
	FOREIGN KEY(event_id) REFERENCES events (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE event_context (
	event_id INTEGER NOT NULL,
	boot_id VARCHAR(64) NOT NULL,
	PRIMARY KEY (event_id),
	FOREIGN KEY(event_id) REFERENCES events (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE audit_details (
	event_id INTEGER NOT NULL,
	audit_timestamp VARCHAR(40) NOT NULL,
	audit_serial VARCHAR(32) NOT NULL,
	record_type VARCHAR(32) NOT NULL,
	login_uid VARCHAR(32),
	real_uid VARCHAR(32),
	effective_uid VARCHAR(32),
	session_id VARCHAR(64),
	syscall VARCHAR(32),
	architecture VARCHAR(32),
	inode VARCHAR(32),
	device VARCHAR(32),
	PRIMARY KEY (event_id),
	FOREIGN KEY(event_id) REFERENCES events (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE alert_policies (
	alert_id INTEGER NOT NULL,
	policy_id VARCHAR(64) NOT NULL,
	PRIMARY KEY (alert_id),
	FOREIGN KEY(alert_id) REFERENCES alerts (id),
	FOREIGN KEY(policy_id) REFERENCES rule_policies (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_bin;

CREATE INDEX ix_alert_policy ON alert_policies (policy_id);

CREATE TABLE alert_reviews (
	id INTEGER NOT NULL AUTO_INCREMENT,
	alert_id INTEGER NOT NULL,
	administrator_id INTEGER NOT NULL,
	action VARCHAR(16) NOT NULL,
	note VARCHAR(1000) NOT NULL,
	timestamp INTEGER NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(alert_id) REFERENCES alerts (id),
	FOREIGN KEY(administrator_id) REFERENCES administrators (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_bin;

CREATE INDEX ix_review_alert_id ON alert_reviews (alert_id, id);

CREATE TABLE host_sessions (
	id VARCHAR(64) NOT NULL,
	host VARCHAR(128) NOT NULL,
	origin VARCHAR(16) NOT NULL,
	boot_id VARCHAR(64) NOT NULL,
	audit_session VARCHAR(32) NOT NULL,
	user_id VARCHAR(64),
	first_seen INTEGER NOT NULL,
	last_seen INTEGER NOT NULL,
	present BOOL NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(user_id) REFERENCES host_users (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE device_events (
	event_id INTEGER NOT NULL,
	device_id VARCHAR(64) NOT NULL,
	snapshot_id VARCHAR(64) NOT NULL,
	PRIMARY KEY (event_id),
	FOREIGN KEY(event_id) REFERENCES events (id),
	FOREIGN KEY(device_id) REFERENCES usb_devices (id),
	FOREIGN KEY(snapshot_id) REFERENCES inventory_snapshots (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE device_decisions (
	id INTEGER NOT NULL AUTO_INCREMENT,
	device_id VARCHAR(64) NOT NULL,
	administrator_id INTEGER NOT NULL,
	approved BOOL NOT NULL,
	note VARCHAR(1000) NOT NULL,
	timestamp INTEGER NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(device_id) REFERENCES usb_devices (id),
	FOREIGN KEY(administrator_id) REFERENCES administrators (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_bin;

CREATE INDEX ix_device_decision ON device_decisions (device_id, id);

CREATE TABLE host_processes (
	id VARCHAR(64) NOT NULL,
	host VARCHAR(128) NOT NULL,
	origin VARCHAR(16) NOT NULL,
	boot_id VARCHAR(64) NOT NULL,
	pid INTEGER NOT NULL,
	started VARCHAR(32) NOT NULL,
	ppid INTEGER NOT NULL,
	parent_id VARCHAR(64),
	session_id VARCHAR(64),
	user_id VARCHAR(64),
	effective_uid VARCHAR(32),
	executable TEXT,
	last_seen INTEGER NOT NULL,
	present BOOL NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(parent_id) REFERENCES host_processes (id),
	FOREIGN KEY(session_id) REFERENCES host_sessions (id),
	FOREIGN KEY(user_id) REFERENCES host_users (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_bin;

CREATE INDEX ix_process_scope_pid ON host_processes (host, origin, boot_id, pid);
